/* CRM Super App v38 responsive workspace. Uses existing callGAS gateway and actor context. */
(function(){
  const $ = id => document.getElementById(id);
  let state = {customers:[],tasks:[],applications:[],kpi:{}};
  const esc = v => String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
  function status(msg,ok=true){const el=$('v38Status');if(!el)return;el.textContent=msg;el.className='rounded-xl p-3 text-sm font-bold '+(ok?'bg-emerald-50 text-emerald-800':'bg-rose-50 text-rose-700');}
  function kpis(){const items=[['Profil nasabah',state.kpi.customers||0,'fa-users'],['Follow-up aktif',state.kpi.openFollowUps||0,'fa-calendar-check'],['Terlambat',state.kpi.overdueFollowUps||0,'fa-clock'],['Pengajuan berjalan',state.kpi.openApplications||0,'fa-folder-open']];$('v38Kpis').innerHTML=items.map(x=>`<div class="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm"><div class="flex justify-between text-slate-500 text-xs font-bold"><span>${x[0]}</span><i class="fa-solid ${x[2]} text-blue-700"></i></div><div class="text-2xl font-black text-[#102B46] mt-2">${x[1]}</div></div>`).join('');}
  window.v38Refresh = async function(){if(typeof activeUser==='undefined'||!activeUser.id)return;try{const data=await callGAS('v38GetWorkspace',{userId:activeUser.id});state=data;kpis();v38RenderCustomers();v38RenderTasks();v38RenderApplications();v38FillCustomerSelects();if(activeUser.role==='ADMIN'){$('v38AdminHealthWrap').classList.remove('hidden');$('v39AdminHealthShortcut')?.classList.remove('hidden');}else{$('v38AdminHealthWrap').classList.add('hidden');$('v39AdminHealthShortcut')?.classList.add('hidden');}$('v38Status').classList.add('hidden');}catch(e){status('Gagal memuat workspace: '+(e.message||e),false);}};
  window.v38RenderCustomers=function(){const q=($('v38CustomerSearch')?.value||'').toLowerCase();const rows=(state.customers||[]).filter(x=>String(x.Nama||'').toLowerCase().includes(q)||String(x.No_HP||'').includes(q));$('v38Customers').innerHTML=rows.slice(0,100).map(x=>`<article class="border border-slate-100 rounded-xl p-3 flex items-start justify-between gap-3"><div class="min-w-0"><p class="font-black text-sm text-slate-800 break-words">${esc(x.Nama)}</p><p class="text-xs text-slate-500 mt-1">${esc(x.No_HP||'Nomor HP belum ada')} · ${esc(x.Segmen||'UMUM')}</p><p class="text-[10px] text-slate-400 mt-1">${esc(x.Alamat||'Alamat belum dicatat')}</p></div><div class="flex flex-col gap-2 shrink-0"><button class="rounded-lg bg-blue-700 text-white px-3 py-2 text-[10px] font-black" onclick="v38OpenCustomerProfile('${esc(x.Nasabah_ID)}')">LIHAT PROFIL</button><button class="rounded-lg bg-blue-50 text-blue-700 px-3 py-2 text-[10px] font-black" onclick="v38ChooseCustomer('${esc(x.Nasabah_ID)}')">PILIH</button></div></article>`).join('')||'<p class="text-xs text-slate-400 text-center p-4">Belum ada profil yang sesuai.</p>';};
  window.v38OpenCustomerProfile=function(id){
    const c=state.customers.find(x=>String(x.Nasabah_ID)===String(id)); if(!c)return;
    const tasks=(state.tasks||[]).filter(x=>String(x.Nasabah_ID)===String(id));
    const apps=(state.applications||[]).filter(x=>String(x.Nasabah_ID)===String(id));
    const legacy=(typeof printData!=='undefined'&&printData.history?printData.history:[]).filter(x=>String(x.nasabah||'').trim().toLowerCase()===String(c.Nama||'').trim().toLowerCase());
    const card=(title,body)=>`<section class="border border-slate-200 rounded-2xl p-4"><h3 class="font-black text-sm text-slate-800 mb-3">${title}</h3>${body}</section>`;
    const list=(arr,fn,empty)=>arr.length?`<div class="space-y-2">${arr.map(fn).join('')}</div>`:`<p class="text-xs text-slate-400">${empty}</p>`;
    const potentials=String(c.Produk_Potensial||'').split(',').map(x=>x.trim()).filter(Boolean);
    $('v38ProfileTitle').textContent=c.Nama||'Profil Nasabah'; $('v38ProfileSub').textContent=[c.No_HP,c.Segmen,c.Status].filter(Boolean).join(' • ');
    $('v38CustomerProfileBody').innerHTML=
      card('INFORMASI NASABAH',`<div class="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm"><div><p class="text-[10px] text-slate-400 font-bold">NOMOR HP</p><p class="font-bold">${esc(c.No_HP||'-')}</p></div><div><p class="text-[10px] text-slate-400 font-bold">EMAIL</p><p class="font-bold break-words">${esc(c.Email||'-')}</p></div><div class="sm:col-span-2"><p class="text-[10px] text-slate-400 font-bold">ALAMAT</p><p>${esc(c.Alamat||'-')}</p></div><div><p class="text-[10px] text-slate-400 font-bold">SEGMEN</p><p>${esc(c.Segmen||'UMUM')}</p></div><div><p class="text-[10px] text-slate-400 font-bold">PIC / OWNER</p><p>${esc(c.Owner_Nama||'-')}</p></div><div class="sm:col-span-2"><p class="text-[10px] text-slate-400 font-bold">CATATAN</p><p>${esc(c.Catatan||'-')}</p></div></div>`)+
      card('PRODUK POTENSIAL',potentials.length?`<div class="flex flex-wrap gap-2">${potentials.map(x=>`<span class="rounded-full bg-blue-50 text-blue-800 px-3 py-2 text-xs font-bold">${esc(x)}</span>`).join('')}</div>`:'<p class="text-xs text-slate-400">Belum ada produk potensial dicatat. Tambahkan pada form profil nasabah.</p>')+
      card(`FOLLOW-UP AKTIF (${tasks.length})`,list(tasks,t=>`<div class="rounded-xl bg-slate-50 p-3"><p class="font-bold text-sm">${esc(t.Produk||'Produk belum ditentukan')}</p><p class="text-xs text-slate-500 mt-1">${esc(t.Jadwal||'-')} • ${esc(t.Prioritas||'NORMAL')}</p><p class="text-xs mt-1">${esc(t.Catatan||'')}</p></div>`,'Belum ada follow-up aktif untuk nasabah ini.'))+
      card(`PENGAJUAN TERKAIT (${apps.length})`,list(apps,a=>`<div class="rounded-xl bg-slate-50 p-3"><div class="flex justify-between gap-2"><p class="font-bold text-sm">${esc(a.Produk||'-')} • ${esc(a.Jenis_Pengajuan||'-')}</p><span class="text-[10px] font-black">${esc(a.Status||'-')}</span></div><p class="text-sm font-black mt-1">${money(a.Plafon_Indikatif)}</p><p class="text-xs text-slate-500 mt-1">Dokumen: ${Number(a.Dokumen_Lengkap)||0}/${Number(a.Dokumen_Wajib)||0} • PIC ${esc(a.PIC_Nama||'-')}</p></div>`,'Belum ada pengajuan terkait.'))+
      card(`RIWAYAT AKTIVITAS CRM (${legacy.length})`,list(legacy.slice(0,30),l=>`<div class="border-l-2 border-blue-600 pl-3 py-1"><p class="text-[10px] text-slate-400">${esc(l.waktu||'')}</p><p class="font-bold text-sm">${esc(l.produk||'Aktivitas')} • ${esc(l.status||'-')}</p><p class="text-xs text-slate-500">${esc(l.aktor||'-')} — ${esc(l.catatan||'Tanpa catatan')}</p></div>`,'Belum ditemukan riwayat aktivitas lama dengan nama yang sama.'));
    $('v38CustomerProfileModal').classList.remove('hidden');
  };
  window.v38CloseCustomerProfile=function(){$('v38CustomerProfileModal')?.classList.add('hidden');};
  window.v38ProfileScheduleFollowUp=function(){const c=state.customers.find(x=>String(x.Nasabah_ID)===String(window.v38CurrentCustomerId));if(c){};const id=$('v38ProfileTitle').dataset.customerId; if(id)v38ChooseCustomer(id);v38CloseCustomerProfile();$('v38FollowForm').scrollIntoView({behavior:'smooth',block:'center'});};
  window.v38ProfileCreateApplication=function(){const id=$('v38ProfileTitle').dataset.customerId;if(id){$('v38AppCustomer').value=id;}v38CloseCustomerProfile();$('v38ApplicationForm').scrollIntoView({behavior:'smooth',block:'center'});};
  window.v38ChooseCustomer=function(id){['v38FollowCustomer','v38AppCustomer'].forEach(k=>{const s=$(k);if(s)s.value=id;});const c=state.customers.find(x=>String(x.Nasabah_ID)===String(id));if(c){$('v38FollowProduct').focus();status('Nasabah dipilih: '+c.Nama,true);}};
  function v38FillCustomerSelects(){['v38FollowCustomer','v38AppCustomer'].forEach(k=>{const sel=$(k);if(!sel)return;const current=sel.value;sel.innerHTML='<option value="">Pilih nasabah *</option>'+(state.customers||[]).map(c=>`<option value="${esc(c.Nasabah_ID)}">${esc(c.Nama)}${c.No_HP?' — '+esc(c.No_HP):''}</option>`).join('');if(current)sel.value=current;});}
  window.v38RenderTasks=function(){const rows=state.tasks||[];$('v38Tasks').innerHTML=rows.slice(0,80).map(t=>{const overdue=t.Jadwal&&new Date(t.Jadwal)<new Date();return `<article class="border rounded-xl p-3 ${overdue?'border-rose-200 bg-rose-50/50':'border-slate-100'}"><div class="flex justify-between gap-2"><div><p class="font-black text-sm text-slate-800">${esc(t.Nama_Nasabah)}</p><p class="text-xs text-slate-500 mt-1">${esc(t.Produk||'Produk belum ditentukan')}</p><p class="text-[10px] mt-2 ${overdue?'text-rose-600':'text-slate-500'}">${overdue?'TERLAMBAT · ':''}${esc(t.Jadwal||'Belum dijadwalkan')} · ${esc(t.Prioritas||'NORMAL')}</p></div><button onclick="v38Complete('${esc(t.FollowUp_ID)}')" class="h-fit rounded-lg bg-emerald-50 text-emerald-700 px-3 py-2 text-[10px] font-black">SELESAI</button></div></article>`;}).join('')||'<p class="text-xs text-slate-400 text-center p-4">Belum ada follow-up aktif.</p>';};
  window.v38RenderApplications=function(){const rows=state.applications||[];$('v38Applications').innerHTML=rows.slice(0,100).map(a=>{const req=Number(a.Dokumen_Wajib)||0,done=Number(a.Dokumen_Lengkap)||0;return `<article class="border border-slate-200 rounded-xl p-4"><div class="flex items-start justify-between gap-2"><div><p class="font-black text-sm text-slate-800">${esc(a.Nama_Nasabah)}</p><p class="text-xs text-blue-700 font-bold mt-1">${esc(a.Produk)} · ${esc(a.Jenis_Pengajuan)}</p></div><span class="rounded-full px-2 py-1 bg-slate-100 text-slate-700 text-[9px] font-black">${esc(a.Status)}</span></div><p class="text-sm font-black text-[#102B46] mt-3">${money(a.Plafon_Indikatif)}</p><div class="mt-3"><div class="flex justify-between text-[10px] text-slate-500 mb-1"><span>Kelengkapan dokumen</span><b>${done}/${req}</b></div><div class="h-2 rounded-full bg-slate-100 overflow-hidden"><div class="h-full bg-blue-600" style="width:${req?Math.min(100,done/req*100):0}%"></div></div></div><p class="text-[10px] text-slate-500 mt-3">PIC: ${esc(a.PIC_Nama||'-')}</p>${a.Catatan?`<p class="text-xs text-slate-600 mt-2">${esc(a.Catatan)}</p>`:''}</article>`;}).join('')||'<p class="text-xs text-slate-400 text-center p-6 md:col-span-3">Belum ada pengajuan.</p>';};
  window.v38Complete=async function(id){const hasil=prompt('Hasil tindak lanjut (ringkas):','Sudah dihubungi');if(hasil===null)return;try{await callGAS('v38CompleteFollowUp',{userId:activeUser.id,id,hasil,status:'SELESAI'});status('Follow-up ditandai selesai.');await v38Refresh();}catch(e){status(e.message||'Gagal menyelesaikan follow-up.',false);}};
  $('v38CustomerForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const payload={nama:$('v38CustName').value,noHp:$('v38CustPhone').value,email:$('v38CustEmail').value,segmen:$('v38CustSegment').value,alamat:$('v38CustAddress').value,potensi:$('v38CustPotential').value,catatan:$('v38CustNote').value};const r=await callGAS('v38SaveCustomer',{userId:activeUser.id,payload});if(r.duplicate){status('Potensi duplikat: '+r.existing.nama+' ('+r.existing.noHp+'). Data baru tidak dibuat.',false);return;}e.target.reset();status(r.message||'Profil disimpan.');await v38Refresh();}catch(err){status(err.message||'Gagal menyimpan profil.',false);}});
  $('v38FollowForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const c=state.customers.find(x=>String(x.Nasabah_ID)===$('v38FollowCustomer').value);if(!c)throw new Error('Pilih nasabah.');const payload={nasabahId:c.Nasabah_ID,namaNasabah:c.Nama,produk:$('v38FollowProduct').value,jadwal:new Date($('v38FollowDue').value).toISOString(),prioritas:$('v38FollowPriority').value,catatan:$('v38FollowNote').value,requestId:(crypto.randomUUID?crypto.randomUUID():'fu-'+Date.now())};const r=await callGAS('v38SaveFollowUp',{userId:activeUser.id,payload});e.target.reset();status(r.message||'Follow-up disimpan.');await v38Refresh();}catch(err){status(err.message||'Gagal menjadwalkan.',false);}});
  $('v38ApplicationForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const payload={nasabahId:$('v38AppCustomer').value,produk:$('v38AppProduct').value,jenis:$('v38AppType').value,status:$('v38AppStatus').value,plafon:$('v38AppLimit').value,dokumenWajib:$('v38AppDocsRequired').value,dokumenLengkap:$('v38AppDocsComplete').value,catatan:$('v38AppNote').value};const r=await callGAS('v38SaveApplication',{userId:activeUser.id,payload});e.target.reset();status(r.message||'Pengajuan disimpan.');await v38Refresh();}catch(err){status(err.message||'Gagal menyimpan pengajuan.',false);}});
  window.v38ExportApplications=function(){const rows=state.applications||[];if(!rows.length){status('Tidak ada pengajuan untuk diekspor.',false);return;}const headers=['Pengajuan_ID','Nama_Nasabah','Produk','Jenis_Pengajuan','Plafon_Indikatif','Status','PIC_Nama','Dokumen_Wajib','Dokumen_Lengkap','Catatan'];const safe=v=>{let s=String(v==null?'':v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const csv='\uFEFF'+[headers,...rows.map(r=>headers.map(h=>r[h]))].map(r=>r.map(safe).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='CRM_Pipeline_Pengajuan_'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(url);callGAS('logReportExport',{userId:activeUser.id,reportType:'V38_APPLICATION_CSV',rowCount:rows.length,periodStart:'',periodEnd:'',adminPin:adminSessionPin}).catch(()=>{});};
  window.v38CheckHealth=async function(){try{const d=await callGAS('v38AdminHealth',{userId:activeUser.id,adminPin:adminSessionPin});$('v38Health').textContent=JSON.stringify(d,null,2);}catch(e){$('v38Health').textContent=e.message||'Pemeriksaan gagal.';}};
})();
